#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check_customer:
    path: /api/customer/login_check
api_login_check_employee:
    path: /api/employee/login_check
jwt_refresh_token:
    path: /api/token_refresh